### ISSUE TITLE
missing field connections_credentials

### ISSUE THREAD

**Issue by makorne** [azat/chdig#1]
Hi! 
Thank you for interesting crate!

I tried deb release, and setup .env  with 
```
CHDIG_URL=127.0.0.1
CLICKHOUSE_USER=xx
CLICKHOUSE_PASSWORD=xx
```
tried  `chdig  -c http://xx:xx@127.0.0.1:8123`

But always got only:

```
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("missing field `connections_credentials`")', src/interpreter/options.rs:91:42`
```

Please share proper credentials example.

**Comment by azat** [comment]
Thank you for the report!

There was a problem in the code, which does not allows to run `chdig` without `connections_credentials` (you can read more about them in https://github.com/ClickHouse/ClickHouse/pull/45715 and https://github.com/ClickHouse/ClickHouse/pull/46480), in a nut shell you can describe all your clusters in the `~/.clickhouse-client/config.xml`.

The issue had been fixed, and now it should work.

However few notes about your command - `chdig  -c http://xx:xx@127.0.0.1:8123` and `chdig` itself:
- it uses TCP protocol, while 8123 is the default HTTP port
- `-c` (`--cluster`) option accept cluster name, not URL. This will turn on cluster mode - that will show you queries from all nodes in the cluster (and not only queries, but also logs, processes, traces, ...). Cluster can be configured in `remote_servers`, see https://clickhouse.com/docs/en/engines/table-engines/special/distributed#distributed-clusters
- maybe you mixed it up with `-C` (`--connection`), but this accept connection name (from `connections_credentials`)
- if you specified `CHDIG_URL` you don't need to specify `--url`

**Comment by azat** [comment]
>The issue had been fixed, and now it should work.

You can use packages from the latest development build:

https://github.com/azat/chdig/releases/tag/latest
