### ISSUE TITLE
Secure connections does not work

### ISSUE THREAD

**Issue by Slach** [azat/chdig#16]
`make build` works fine
```
./target/chdig --url=tcp://XXX:XXX@github.demo.altinity.cloud:9440/?secure=true
```

return 101 exit code and
```
[flexi_logger][ERRCODE::Time] flexi_logger has to work with UTC rather than with local time, caused by IndeterminateOffset
See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#time
```

successfull connect with 
```
clickhouse-client --user=XXX --password=XXX -h github.demo.altinity.cloud --port 9440 --secure
```

**Comment by azat** [comment]
```
[flexi_logger][ERRCODE::Time] flexi_logger has to work with UTC rather than with local time, caused by IndeterminateOffset
See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#time
```

This is not an error (this is due to musl build)
Was it the full stacktrace?

Actually I guess the reason is that as of now `tls` layer is not enabled for clickhouse-rs.
And this will bring extra dependencies, need to take a look...

**Comment by azat** [comment]
For now you could try to build from sources, using something like this - https://github.com/azat/chdig/pull/17#issuecomment-1859970929

**Comment by Slach** [comment]
> Was it the full stacktrace?

How to get full stacktrace?

**Comment by azat** [comment]
> How to get full stacktrace?

Usually `RUST_BACKTRACE=1` should be enough, but maybe you cannot catch it because terminal mode had been switched already...

**Comment by azat** [comment]
For now you can use binaries from the latest release - https://github.com/azat/chdig/releases/tag/latest
Here is a separate issue to support openssl 3.0 - https://github.com/azat/chdig/issues/18

**Comment by azat** [comment]
@Slach FYI I'm going to replace native-tls (openssl) with rustls - https://github.com/azat/chdig/pull/26 (hope that it will not break anything for you)

**Comment by Slach** [comment]
@azat 0.6.1 works ok, will check `rustls` on the next release, thanks for your effort

**Comment by azat** [comment]
FYI I would recommend you to use always latest available version, and don't stick to releases (since sometimes I may forgot about this routine).

Anyway here is the link to the latest release (updated on each push to the default branch - `main`) - https://github.com/azat/chdig/releases/tag/latest

P.S. and now this release contains rustls already.
