### ISSUE TITLE
chdig 0.3.0 doesn't start

### ISSUE THREAD

**Issue by makorne** [azat/chdig#3]
Hi!
After upgrade on debian from just worked chdig 0.2.0 to chdig 0.3.0:

chdig
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/interpreter/options.rs:216:49
```
Cheers!

**Comment by azat** [comment]
Hi @makorne, thank you for the report!
Yep, the problem was with the url API, should be fixed in the latest release (this release is updated on each push), you can download it here - https://github.com/azat/chdig/releases/tag/latest
Or you can always build from sources.

**Comment by makorne** [comment]
Do you see  [this](https://gist.github.com/sanchezzzhak/511fd140e8809857f8f1d84ddb937015) code? 
May be something useful for chdig.

Thank you for your great work!

**Comment by azat** [comment]
>Do you see [this](https://gist.github.com/sanchezzzhak/511fd140e8809857f8f1d84ddb937015) code?

Thanks, I have my own set of onelinears for this.
It is not a problem to show something, right now I'm still trying to figure out what is useful (and hence should be shown) and what is not.
There are already set of todos in the code and https://github.com/azat/chdig/blob/main/TODO.md

If you have some suggestions what will be useful to add, feel free to create new issue!
