### ISSUE TITLE
Standalone binary distribution option

### ISSUE THREAD

**Issue by filimonov** [azat/chdig#48]
Because of the distribution in packages it requires to have root access to install / use that, which is not handy in some envs.

The tool itself seems to be statically linked and have no external deps, so should have no issues even when started from the home dir.

**Comment by filimonov** [comment]
Ideally something like 

```
wget https://github.com/azat/chdig/releases/latest/chdig-amd64
chmod +x chdig-amd64
./chdig-amd64
```

It can also be tar.gz (then you can include the bash completion).

you have tar.zst - but zstd is not preinstalled / rarely available (so again requires root to install it).

**Comment by filimonov** [comment]
Also gz for windows distribution is also not a natural choice (use zip)

**Comment by filimonov** [comment]
workaround if dpkg is available

```
wget https://github.com/azat/chdig/releases/download/latest/chdig-latest_amd64.deb
dpkg -x chdig-latest_amd64.deb /tmp/chdig
/chdig/usr/bin/chdig
```

but for alpine based rootless containers it doesn't help.

**Comment by azat** [comment]
@filimonov see https://github.com/azat/chdig/releases/tag/latest
