### ISSUE TITLE
show the query without editor installed

### ISSUE THREAD

**Issue by filimonov** [azat/chdig#56]
vim can be missing, still want to see the 'raw' query (even if will not be able to edit it)

![image](https://github.com/azat/chdig/assets/1549571/9151a786-5a18-42cf-972f-29e4d775ac4f)

explain syntax is the closest (but not the same).

**Comment by filimonov** [comment]
Also would be great it it will be possible to copy the query (using mouse or smth like that).

**Comment by azat** [comment]
>Also would be great it it will be possible to copy the query (using mouse? right now the mouse actions to be hooked).

Multiple terminals has different bindings to disable mouse mode on selection, for instance the one I use (alacritty) it has Shift for this, so just press Ctrl Shift select with mouse any text.

**Comment by azat** [comment]
But I agree that no-mouse mode should be supported and I had it in the previous version of chdig (not public), but due to some changes in abstractions it is not implemented yet

**Comment by azat** [comment]
>explain syntax is the closest (but not the same).

Yes, but have you met such queries in real life?

**Comment by filimonov** [comment]
> > explain syntax is the closest (but not the same).
> 
> Yes, but have you met such queries in real life?

Try this one:

```
explain syntax select * from system.parts p left join system.tables t on (p.database = t.database and p.table = t.name) left join system.databases d on (t.database = d.name);
```
