### ISSUE TITLE
EXPLAIN may fail if SETTINGs are used in query

### ISSUE THREAD

**Issue by filimonov** [azat/chdig#57]
didn't check if it's the clickhouse of chgid issue, but that's poor:

![image](https://github.com/azat/chdig/assets/1549571/60c47e05-662d-4697-a2c8-caed8dc1544b)

![image](https://github.com/azat/chdig/assets/1549571/3935aa1d-2e60-4bb0-b2bf-37e745b30cf3)

**Comment by azat** [comment]
Not sure that I understand what your problem is.
But likely you hit this problem - https://github.com/azat/chdig/blob/aed35642b3792adcb09642a98e8c4e68942adf95/src/interpreter/clickhouse.rs#L624-L633

**Comment by azat** [comment]
I also found a typo there, patch - https://github.com/azat/chdig/pull/61/commits/3aa60843bc224bbd75b204b9b73106c899fc523a, fixed in https://github.com/azat/chdig/pull/61

Does it fixes the issue for you?

(latest release already contains this fix - https://github.com/azat/chdig/releases/tag/latest)
